<?php
declare(strict_types=1);

namespace App\Home;

use Core\Framework\Module;
use Core\Framework\Attributes\Module as Mod;
use Core\Framework\Attributes\Required;

#[Mod(
    slug: 'home',
    name: 'Home',
    route: '/',
    template: true,
    templateLabel: 'Página · Home',
)]
#[Required]
final class HomeModule extends Module
{
    public function fields(): void
    {
        acf_add_local_field_group([
            'key'      => 'group_home',
            'title'    => 'Home',
            'location' => [[
                ['param' => 'page_template', 'operator' => '==', 'value' => 'fw:home'],
            ]],
            'fields' => [
                // ── Hero (carrossel) ──────────────────────────────────────
                [
                    'key'          => 'field_home_hero_slides',
                    'name'         => 'hero_slides',
                    'label'        => 'Hero — Slides do Carrossel',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Slide',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_home_hero_slide_imagem',
                            'name'          => 'imagem',
                            'label'         => 'Imagem de Fundo',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_imagem_mobile',
                            'name'          => 'imagem_mobile',
                            'label'         => 'Imagem Mobile',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                            'instructions'  => 'Imagem exibida na parte inferior do slide no mobile (PNG com fundo transparente, proporção 393×459).',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_eyebrow',
                            'name'          => 'eyebrow',
                            'label'         => 'Subtítulo (H1)',
                            'type'          => 'text',
                            'instructions'  => 'Texto curto exibido acima do título. Renderizado como H1 da página (o Título abaixo vira H2).',
                            'default_value' => 'Diagnóstico Veterinário',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_titulo',
                            'name'          => 'titulo',
                            'label'         => 'Título',
                            'type'          => 'text',
                            'required'      => 1,
                            'default_value' => 'Diagnóstico Veterinário com Precisão, Agilidade e Confiança',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_subtitulo',
                            'name'          => 'subtitulo',
                            'label'         => 'Subtítulo',
                            'type'          => 'textarea',
                            'rows'          => 2,
                            'default_value' => 'Há 10 anos apoiando médicos-veterinários com tecnologia e qualidade.',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_cta_primario_texto',
                            'name'          => 'cta_primario_texto',
                            'label'         => 'CTA Primário — Texto',
                            'type'          => 'text',
                            'default_value' => 'Quero ser parceiro',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_cta_primario_link',
                            'name'          => 'cta_primario_link',
                            'label'         => 'CTA Primário — Link',
                            'type'          => 'text',
                            'default_value' => '#',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_cta_secundario_texto',
                            'name'          => 'cta_secundario_texto',
                            'label'         => 'CTA Secundário — Texto',
                            'type'          => 'text',
                            'default_value' => 'Acessar resultados',
                        ],
                        [
                            'key'           => 'field_home_hero_slide_cta_secundario_link',
                            'name'          => 'cta_secundario_link',
                            'label'         => 'CTA Secundário — Link',
                            'type'          => 'text',
                            'default_value' => '#',
                        ],
                    ],
                ],
                [
                    'key'           => 'field_home_hero_autoplay',
                    'name'          => 'hero_autoplay',
                    'label'         => 'Hero — Autoplay do Carrossel',
                    'type'          => 'true_false',
                    'ui'            => 1,
                    'default_value' => 1,
                ],
                [
                    'key'               => 'field_home_hero_intervalo',
                    'name'              => 'hero_intervalo',
                    'label'             => 'Hero — Intervalo do Autoplay (ms)',
                    'type'              => 'number',
                    'default_value'     => 6000,
                    'min'               => 2000,
                    'step'              => 500,
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_home_hero_autoplay',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],

                // ── Serviços ──────────────────────────────────────────────
                [
                    'key'           => 'field_home_servicos_eyebrow',
                    'name'          => 'servicos_eyebrow',
                    'label'         => 'Serviços — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Nossos Serviços',
                ],
                [
                    'key'           => 'field_home_servicos_titulo',
                    'name'          => 'servicos_titulo',
                    'label'         => 'Serviços — Título',
                    'type'          => 'text',
                    'default_value' => 'Tecnologia e cuidado a serviço da saúde animal',
                ],
                [
                    'key'          => 'field_home_servicos_itens',
                    'name'         => 'servicos_itens',
                    'label'        => 'Serviços — Itens',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Serviço',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_home_servicos_item_imagem',
                            'name'          => 'imagem',
                            'label'         => 'Imagem',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                        ],
                        [
                            'key'           => 'field_home_servicos_item_titulo',
                            'name'          => 'titulo',
                            'label'         => 'Título',
                            'type'          => 'text',
                            'required'      => 1,
                            'default_value' => '',
                        ],
                        [
                            'key'           => 'field_home_servicos_item_descricao',
                            'name'          => 'descricao',
                            'label'         => 'Descrição',
                            'type'          => 'textarea',
                            'rows'          => 2,
                            'default_value' => '',
                        ],
                        [
                            'key'           => 'field_home_servicos_item_cta_texto',
                            'name'          => 'cta_texto',
                            'label'         => 'CTA — Texto',
                            'type'          => 'text',
                            'default_value' => 'Agendar',
                        ],
                        [
                            'key'           => 'field_home_servicos_item_cta_link',
                            'name'          => 'cta_link',
                            'label'         => 'CTA — Link',
                            'type'          => 'text',
                            'default_value' => '#',
                        ],
                    ],
                ],
                [
                    'key'           => 'field_home_servicos_cta_texto',
                    'name'          => 'servicos_cta_texto',
                    'label'         => 'Serviços — CTA Final (Texto)',
                    'type'          => 'text',
                    'default_value' => 'Ver todos exames',
                ],
                [
                    'key'           => 'field_home_servicos_cta_link',
                    'name'          => 'servicos_cta_link',
                    'label'         => 'Serviços — CTA Final (Link)',
                    'type'          => 'text',
                    'default_value' => '#',
                ],

                // ── Exames (acordeão) ─────────────────────────────────────
                [
                    'key'           => 'field_home_exames_eyebrow',
                    'name'          => 'exames_eyebrow',
                    'label'         => 'Exames — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Exames',
                ],
                [
                    'key'           => 'field_home_exames_titulo',
                    'name'          => 'exames_titulo',
                    'label'         => 'Exames — Título',
                    'type'          => 'text',
                    'default_value' => 'Tipos de exames realizados',
                ],
                [
                    'key'           => 'field_home_exames_descricao',
                    'name'          => 'exames_descricao',
                    'label'         => 'Exames — Descrição',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'O Genoma oferece um portfólio completo de exames, organizado nas seguintes áreas:',
                ],
                [
                    'key'          => 'field_home_exames_categorias',
                    'name'         => 'exames_categorias',
                    'label'        => 'Exames — Categorias (acordeão)',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Categoria',
                    'collapsed' => 'field_home_exames_categoria_titulo',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_home_exames_categoria_titulo',
                            'name'          => 'titulo',
                            'label'         => 'Título da Categoria',
                            'type'          => 'text',
                            'required'      => 1,
                            'default_value' => '',
                        ],
                        [
                            'key'           => 'field_home_exames_categoria_texto',
                            'name'          => 'texto',
                            'label'         => 'Texto (opcional)',
                            'type'          => 'textarea',
                            'rows'          => 2,
                            'default_value' => '',
                        ],
                        [
                            'key'          => 'field_home_exames_categoria_itens',
                            'name'         => 'itens',
                            'label'        => 'Itens (exames desta categoria)',
                            'type'         => 'repeater',
                            'layout'       => 'block',
                            'min'          => 0,
                            'max'          => 0,
                            'button_label' => 'Adicionar Exame',
                            'sub_fields'   => [
                                [
                                    'key'           => 'field_home_exames_item_nome',
                                    'name'          => 'nome',
                                    'label'         => 'Nome do Exame',
                                    'type'          => 'text',
                                    'required'      => 1,
                                    'default_value' => '',
                                ],
                                [
                                    'key'           => 'field_home_exames_item_prazo',
                                    'name'          => 'prazo',
                                    'label'         => 'Prazo',
                                    'type'          => 'text',
                                    'default_value' => '7 Dias',
                                ],
                                [
                                    'key'           => 'field_home_exames_item_amostra',
                                    'name'          => 'amostra',
                                    'label'         => 'Tipo de Amostra',
                                    'type'          => 'text',
                                    'default_value' => 'Lâminas',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'key'           => 'field_home_exames_cta_texto',
                    'name'          => 'exames_cta_texto',
                    'label'         => 'Exames — CTA Final (Texto)',
                    'type'          => 'text',
                    'default_value' => 'Ver todos exames',
                ],
                [
                    'key'           => 'field_home_exames_cta_link',
                    'name'          => 'exames_cta_link',
                    'label'         => 'Exames — CTA Final (Link)',
                    'type'          => 'text',
                    'default_value' => '#',
                ],

                // ── Sobre o Genoma ────────────────────────────────────────
                [
                    'key'           => 'field_home_sobre_eyebrow',
                    'name'          => 'sobre_eyebrow',
                    'label'         => 'Sobre — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Sobre o Genoma',
                ],
                [
                    'key'           => 'field_home_sobre_titulo',
                    'name'          => 'sobre_titulo',
                    'label'         => 'Sobre — Título',
                    'type'          => 'text',
                    'default_value' => '10 anos fortalecendo a medicina veterinária',
                ],
                [
                    'key'           => 'field_home_sobre_foto_1',
                    'name'          => 'sobre_foto_1',
                    'label'         => 'Sobre — Foto 1',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'           => 'field_home_sobre_foto_2',
                    'name'          => 'sobre_foto_2',
                    'label'         => 'Sobre — Foto 2',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'           => 'field_home_sobre_foto_3',
                    'name'          => 'sobre_foto_3',
                    'label'         => 'Sobre — Foto 3',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'           => 'field_home_sobre_texto',
                    'name'          => 'sobre_texto',
                    'label'         => 'Sobre — Texto (parágrafos separados por linha em branco)',
                    'type'          => 'textarea',
                    'rows'          => 6,
                    'new_lines'     => '',
                    'default_value' => "O Genoma é um centro de diagnóstico veterinário estruturado para oferecer exames laboratoriais e diagnósticos por imagem com precisão, segurança e rapidez.\n\nAtuamos como parceiros estratégicos de clínicas e hospitais veterinários, contribuindo diretamente para decisões clínicas mais assertivas.\n\nCom tecnologia moderna, controle rigoroso de qualidade e equipe especializada, entregamos resultados confiáveis todos os dias.",
                ],
                [
                    'key'           => 'field_home_sobre_destaque',
                    'name'          => 'sobre_destaque',
                    'label'         => 'Sobre — Frase de Destaque',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'Mais do que exames, entregamos parceria, suporte técnico e confiança para a rotina clínica.',
                ],
                [
                    'key'          => 'field_home_sobre_diferenciais',
                    'name'         => 'sobre_diferenciais',
                    'label'        => 'Sobre — Diferenciais (cards)',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Diferencial',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_home_sobre_diferencial_icone',
                            'name'          => 'icone',
                            'label'         => 'Ícone',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'thumbnail',
                            'mime_types'    => 'svg,png',
                        ],
                        [
                            'key'           => 'field_home_sobre_diferencial_titulo',
                            'name'          => 'titulo',
                            'label'         => 'Título',
                            'type'          => 'text',
                            'required'      => 1,
                            'default_value' => '',
                        ],
                        [
                            'key'           => 'field_home_sobre_diferencial_descricao',
                            'name'          => 'descricao',
                            'label'         => 'Descrição',
                            'type'          => 'textarea',
                            'rows'          => 3,
                            'default_value' => '',
                        ],
                    ],
                ],

                // ── Diferenciais ──────────────────────────────────────────
                [
                    'key'           => 'field_home_diferenciais_eyebrow',
                    'name'          => 'diferenciais_eyebrow',
                    'label'         => 'Diferenciais — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Diferenciais',
                ],
                [
                    'key'           => 'field_home_diferenciais_titulo',
                    'name'          => 'diferenciais_titulo',
                    'label'         => 'Diferenciais — Título',
                    'type'          => 'text',
                    'default_value' => 'Por que escolher o Genoma?',
                ],
                [
                    'key'           => 'field_home_diferenciais_imagem',
                    'name'          => 'diferenciais_imagem',
                    'label'         => 'Diferenciais — Imagem de Fundo',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'          => 'field_home_diferenciais_itens',
                    'name'         => 'diferenciais_itens',
                    'label'        => 'Diferenciais — Itens (cards)',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Diferencial',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_home_diferenciais_item_icone',
                            'name'          => 'icone',
                            'label'         => 'Ícone',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'thumbnail',
                            'mime_types'    => 'svg,png',
                        ],
                        [
                            'key'           => 'field_home_diferenciais_item_titulo',
                            'name'          => 'titulo',
                            'label'         => 'Texto',
                            'type'          => 'text',
                            'required'      => 1,
                            'default_value' => '',
                        ],
                    ],
                ],

                // ── Estrutura ─────────────────────────────────────────────
                [
                    'key'           => 'field_home_estrutura_eyebrow',
                    'name'          => 'estrutura_eyebrow',
                    'label'         => 'Estrutura — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Estrutura / Tecnologia',
                ],
                [
                    'key'           => 'field_home_estrutura_titulo',
                    'name'          => 'estrutura_titulo',
                    'label'         => 'Estrutura — Título',
                    'type'          => 'text',
                    'default_value' => 'Tecnologia que gera confiança',
                ],
                [
                    'key'           => 'field_home_estrutura_descricao',
                    'name'          => 'estrutura_descricao',
                    'label'         => 'Estrutura — Descrição',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'O Genoma é um centro de diagnóstico veterinário estruturado para oferecer exames laboratoriais e diagnósticos por imagem',
                ],
                [
                    'key'           => 'field_home_estrutura_foto_1',
                    'name'          => 'estrutura_foto_1',
                    'label'         => 'Estrutura — Foto 1',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'           => 'field_home_estrutura_foto_2',
                    'name'          => 'estrutura_foto_2',
                    'label'         => 'Estrutura — Foto 2',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'           => 'field_home_estrutura_foto_3',
                    'name'          => 'estrutura_foto_3',
                    'label'         => 'Estrutura — Foto 3',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],

                // ── Depoimentos (carrossel) ──────────────────────────────
                [
                    'key'           => 'field_home_depoimentos_eyebrow',
                    'name'          => 'depoimentos_eyebrow',
                    'label'         => 'Depoimentos — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Estrutura / Tecnologia',
                ],
                [
                    'key'           => 'field_home_depoimentos_titulo',
                    'name'          => 'depoimentos_titulo',
                    'label'         => 'Depoimentos — Título',
                    'type'          => 'text',
                    'default_value' => 'O que nossos clientes dizem',
                ],
                [
                    'key'          => 'field_home_depoimentos_itens',
                    'name'         => 'depoimentos_itens',
                    'label'        => 'Depoimentos — Itens (carrossel)',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Depoimento',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_home_depoimentos_item_icone',
                            'name'          => 'icone',
                            'label'         => 'Ícone',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'thumbnail',
                            'mime_types'    => 'svg,png',
                        ],
                        [
                            'key'           => 'field_home_depoimentos_item_texto',
                            'name'          => 'texto',
                            'label'         => 'Depoimento',
                            'type'          => 'textarea',
                            'rows'          => 4,
                            'required'      => 1,
                            'default_value' => '',
                        ],
                        [
                            'key'           => 'field_home_depoimentos_item_nome',
                            'name'          => 'nome',
                            'label'         => 'Nome do Cliente',
                            'type'          => 'text',
                            'required'      => 1,
                            'default_value' => '',
                        ],
                    ],
                ],
                [
                    'key'           => 'field_home_depoimentos_autoplay',
                    'name'          => 'depoimentos_autoplay',
                    'label'         => 'Depoimentos — Autoplay do Carrossel',
                    'type'          => 'true_false',
                    'ui'            => 1,
                    'default_value' => 1,
                ],
                [
                    'key'               => 'field_home_depoimentos_intervalo',
                    'name'              => 'depoimentos_intervalo',
                    'label'             => 'Depoimentos — Intervalo do Autoplay (ms)',
                    'type'              => 'number',
                    'default_value'     => 6000,
                    'min'               => 2000,
                    'step'              => 500,
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_home_depoimentos_autoplay',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],

                // ── Rodapé (sobrescreve o CTA do banner só nesta página) ───
                [
                    'key'           => 'field_home_footer_cta_titulo',
                    'name'          => 'footer_cta_titulo',
                    'label'         => 'Rodapé — CTA Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Sobrescreve o título do banner de CTA do rodapé só nesta página. Deixe em branco para usar o padrão de Opções do Tema.',
                    'default_value' => 'Cuidado começa com diagnóstico preciso.',
                ],
                [
                    'key'           => 'field_home_footer_cta_primario_texto',
                    'name'          => 'footer_cta_primario_texto',
                    'label'         => 'Rodapé — CTA Primário (Texto)',
                    'type'          => 'text',
                    'instructions'  => 'Sobrescreve o texto do botão principal do banner de CTA do rodapé só nesta página. Deixe em branco para usar o padrão de Opções do Tema.',
                    'default_value' => 'Agendar Exame',
                ],
                [
                    'key'           => 'field_home_footer_cta_primario_link',
                    'name'          => 'footer_cta_primario_link',
                    'label'         => 'Rodapé — CTA Primário (Link)',
                    'type'          => 'text',
                    'default_value' => '#',
                ],
                [
                    'key'           => 'field_home_footer_cta_mostrar_secundario',
                    'name'          => 'footer_cta_mostrar_secundario',
                    'label'         => 'Rodapé — Mostrar Botão Secundário',
                    'type'          => 'true_false',
                    'ui'            => 1,
                    'default_value' => 1,
                ],
                [
                    'key'               => 'field_home_footer_cta_secundario_texto',
                    'name'              => 'footer_cta_secundario_texto',
                    'label'             => 'Rodapé — CTA Secundário (Texto)',
                    'type'              => 'text',
                    'default_value'     => 'Fale Conosco',
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_home_footer_cta_mostrar_secundario',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],
                [
                    'key'               => 'field_home_footer_cta_secundario_link',
                    'name'              => 'footer_cta_secundario_link',
                    'label'             => 'Rodapé — CTA Secundário (Link)',
                    'type'              => 'text',
                    'default_value'     => '#',
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_home_footer_cta_mostrar_secundario',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }
}
