<?php
declare(strict_types=1);

namespace App\Responsavel;

use Core\Framework\Module;
use Core\Framework\Attributes\Module as Mod;

#[Mod(
    slug: 'responsavel',
    name: 'Responsável',
    route: '/responsavel',
    template: true,
    templateLabel: 'Página · Responsável',
)]
final class ResponsavelModule extends Module
{
    public function fields(): void
    {
        acf_add_local_field_group([
            'key'      => 'group_responsavel',
            'title'    => 'Responsável',
            'location' => [[
                ['param' => 'page_template', 'operator' => '==', 'value' => 'fw:responsavel'],
            ]],
            'fields' => [
                // ── Hero (carrossel) ──────────────────────────────────────
                [
                    'key'          => 'field_responsavel_hero_slides',
                    'instructions' => 'Cada linha é um slide. Com 2 ou mais slides aparecem as setas e as bolinhas de navegação. Sem nenhum slide, o topo da página não aparece.',
                    'name'         => 'hero_slides',
                    'label'        => 'Hero — Slides do Carrossel',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Slide',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_responsavel_hero_slide_imagem',
                            'instructions'  => 'Foto do slide, exibida ao lado do texto. Prefira PNG com fundo transparente ou foto com o assunto à direita.',
                            'name'          => 'imagem',
                            'label'         => 'Imagem',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_eyebrow',
                            'name'          => 'eyebrow',
                            'label'         => 'Etiqueta (H1)',
                            'type'          => 'text',
                            'instructions'  => 'Renderizado como H1 da página apenas no primeiro slide (o Título abaixo é H2).',
                            'default_value' => 'Responsável',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_titulo',
                            'name'          => 'titulo',
                            'label'         => 'Título',
                            'type'          => 'textarea',
                            'rows'          => 2,
                            'required'      => 1,
                            'instructions'  => 'Use uma quebra de linha para controlar onde o título deve quebrar.',
                            'default_value' => 'Cuidado, confiança e diagnóstico preciso para o seu pet',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_subtitulo',
                            'instructions'  => 'Frase de apoio abaixo do título.',
                            'name'          => 'subtitulo',
                            'label'         => 'Subtítulo',
                            'type'          => 'textarea',
                            'rows'          => 2,
                            'default_value' => 'Suporte técnico, agilidade e condições especiais para médicos-veterinários que buscam excelência no cuidado.',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_cta_primario_texto',
                            'instructions'  => 'Texto do botão roxo. Em branco, o botão não aparece.',
                            'name'          => 'cta_primario_texto',
                            'label'         => 'CTA Primário — Texto',
                            'type'          => 'text',
                            'default_value' => 'Fale conosco',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_cta_primario_link',
                            'instructions'  => 'Endereço completo do botão, começando com https:// (ou o endereço de uma página do site).',
                            'name'          => 'cta_primario_link',
                            'label'         => 'CTA Primário — Link',
                            'type'          => 'text',
                            'default_value' => '#',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_cta_secundario_texto',
                            'instructions'  => 'Texto do botão branco. Em branco, o botão não aparece.',
                            'name'          => 'cta_secundario_texto',
                            'label'         => 'CTA Secundário — Texto',
                            'type'          => 'text',
                            'default_value' => 'Nossos serviços',
                        ],
                        [
                            'key'           => 'field_responsavel_hero_slide_cta_secundario_link',
                            'instructions'  => 'Endereço completo do botão, começando com https:// (ou o endereço de uma página do site).',
                            'name'          => 'cta_secundario_link',
                            'label'         => 'CTA Secundário — Link',
                            'type'          => 'text',
                            'default_value' => '#',
                        ],
                    ],
                ],
                [
                    'key'           => 'field_responsavel_hero_autoplay',
                    'instructions'  => 'Ligado: os slides passam sozinhos (pausam quando o mouse está sobre eles).',
                    'name'          => 'hero_autoplay',
                    'label'         => 'Hero — Autoplay do Carrossel',
                    'type'          => 'true_false',
                    'ui'            => 1,
                    'default_value' => 1,
                ],
                [
                    'key'               => 'field_responsavel_hero_intervalo',
                    'instructions'      => 'Tempo de cada slide em milissegundos: 6000 = 6 segundos. Mínimo 2000.',
                    'name'              => 'hero_intervalo',
                    'label'             => 'Hero — Intervalo do Autoplay (ms)',
                    'type'              => 'number',
                    'default_value'     => 6000,
                    'min'               => 2000,
                    'step'              => 500,
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_responsavel_hero_autoplay',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],

                // ── Suporte ───────────────────────────────────────────────
                [
                    'key'           => 'field_responsavel_suporte_eyebrow',
                    'instructions'  => 'Texto curto exibido acima do título da seção (ex.: SERVIÇOS).',
                    'name'          => 'suporte_eyebrow',
                    'label'         => 'Suporte — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Suporte técnico',
                ],
                [
                    'key'           => 'field_responsavel_suporte_titulo',
                    'name'          => 'suporte_titulo',
                    'label'         => 'Suporte — Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Use uma quebra de linha para controlar onde o título deve quebrar.',
                    'default_value' => 'Como funciona o atendimento ao Responsável?',
                ],
                [
                    'key'           => 'field_responsavel_suporte_texto',
                    'instructions'  => 'Use uma linha em branco para separar os parágrafos.',
                    'name'          => 'suporte_texto',
                    'label'         => 'Suporte — Texto',
                    'type'          => 'textarea',
                    'rows'          => 4,
                    'default_value' => "Os exames são sempre solicitados por um médico-veterinário.\nO Genoma realiza as análises laboratoriais e fornece os resultados ao profissional responsável, que é quem fará a avaliação clínica e as orientações necessárias para o tratamento do animal.",
                ],
                [
                    'key'           => 'field_responsavel_suporte_quote',
                    'instructions'  => 'Frase em destaque, exibida entre linhas.',
                    'name'          => 'suporte_quote',
                    'label'         => 'Suporte — Quote/Destaque',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => 'Garantimos segurança, ética e um acompanhamento adequado em cada caso.',
                ],
                [
                    'key'           => 'field_responsavel_suporte_imagem_1',
                    'instructions'  => 'Foto vertical (retrato), à esquerda.',
                    'name'          => 'suporte_imagem_1',
                    'label'         => 'Suporte — Imagem 1 (retrato)',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],
                [
                    'key'           => 'field_responsavel_suporte_imagem_2',
                    'instructions'  => 'Foto horizontal (paisagem), à direita.',
                    'name'          => 'suporte_imagem_2',
                    'label'         => 'Suporte — Imagem 2 (paisagem)',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],

                // ── Planos ────────────────────────────────────────────────
                [
                    'key'           => 'field_responsavel_planos_eyebrow',
                    'instructions'  => 'Texto curto exibido acima do título da seção (ex.: SERVIÇOS).',
                    'name'          => 'planos_eyebrow',
                    'label'         => 'Planos — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Planos de saúde atendidos',
                ],
                [
                    'key'           => 'field_responsavel_planos_titulo',
                    'name'          => 'planos_titulo',
                    'label'         => 'Planos — Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Use uma quebra de linha para controlar onde o título deve quebrar.',
                    'default_value' => 'O Genoma atende os seguintes planos de saúde pet:',
                ],
                [
                    'key'          => 'field_responsavel_planos_logos',
                    'instructions' => 'Cada linha é o logo de um plano de saúde pet aceito.',
                    'name'         => 'planos_logos',
                    'label'        => 'Planos — Logos',
                    'type'         => 'repeater',
                    'layout'       => 'table',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Logo',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_responsavel_planos_logo_imagem',
                            'instructions'  => 'Logo do plano em PNG ou SVG com fundo transparente.',
                            'name'          => 'imagem',
                            'label'         => 'Logo',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                        ],
                        [
                            'key'           => 'field_responsavel_planos_logo_nome',
                            'instructions'  => 'Nome do plano. Não aparece na tela: é lido por leitores de tela e pelo Google.',
                            'name'          => 'nome',
                            'label'         => 'Nome (texto alternativo)',
                            'type'          => 'text',
                        ],
                    ],
                ],

                // ── Exames ────────────────────────────────────────────────
                [
                    'key'           => 'field_responsavel_exames_eyebrow',
                    'instructions'  => 'Texto curto exibido acima do título da seção (ex.: SERVIÇOS).',
                    'name'          => 'exames_eyebrow',
                    'label'         => 'Exames — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Exames',
                ],
                [
                    'key'           => 'field_responsavel_exames_titulo',
                    'name'          => 'exames_titulo',
                    'label'         => 'Exames — Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Use uma quebra de linha para controlar onde o título deve quebrar.',
                    'default_value' => 'Preparação para exames: jejum',
                ],
                [
                    'key'           => 'field_responsavel_exames_texto',
                    'instructions'  => 'Use uma linha em branco para separar os parágrafos.',
                    'name'          => 'exames_texto',
                    'label'         => 'Exames — Texto',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'Para garantir resultados mais precisos, alguns exames exigem jejum alimentar:',
                ],
                [
                    'key'          => 'field_responsavel_exames_itens',
                    'instructions' => 'Cada linha é uma orientação de jejum ou preparo, com ícone.',
                    'name'         => 'exames_itens',
                    'label'        => 'Exames — Itens de Jejum',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Item',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_responsavel_exames_item_icone',
                            'instructions'  => 'Ícone em SVG ou PNG com fundo transparente.',
                            'name'          => 'icone',
                            'label'         => 'Ícone',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                        ],
                        [
                            'key'           => 'field_responsavel_exames_item_texto',
                            'name'          => 'texto',
                            'label'         => 'Texto',
                            'type'          => 'text',
                            'instructions'  => 'Parte normal do texto, incluindo o ":" final quando houver.',
                        ],
                        [
                            'key'           => 'field_responsavel_exames_item_destaque',
                            'name'          => 'destaque',
                            'label'         => 'Texto em destaque',
                            'type'          => 'text',
                            'instructions'  => 'Parte exibida em negrito (ex: jejum de 8 horas).',
                        ],
                    ],
                ],
                [
                    'key'           => 'field_responsavel_exames_rodape',
                    'instructions'  => 'Observação exibida abaixo da lista (ex.: em caso de dúvida, fale com o veterinário).',
                    'name'          => 'exames_rodape',
                    'label'         => 'Exames — Texto de Rodapé',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'Sempre siga também as orientações do médico-veterinário, pois em alguns casos podem existir recomendações específicas para o seu pet.',
                ],
                [
                    'key'           => 'field_responsavel_exames_imagem',
                    'instructions'  => 'Foto de fundo da seção, horizontal, com pelo menos 1920 px de largura.',
                    'name'          => 'exames_imagem',
                    'label'         => 'Exames — Imagem de Fundo',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],

                // ── Serviços ──────────────────────────────────────────────
                [
                    'key'           => 'field_responsavel_servicos_eyebrow',
                    'instructions'  => 'Texto curto exibido acima do título da seção (ex.: SERVIÇOS).',
                    'name'          => 'servicos_eyebrow',
                    'label'         => 'Serviços — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Nossos Serviços',
                ],
                [
                    'key'           => 'field_responsavel_servicos_titulo',
                    'name'          => 'servicos_titulo',
                    'label'         => 'Serviços — Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Use uma quebra de linha para controlar onde o título deve quebrar.',
                    'default_value' => 'Tipos de exames realizados',
                ],
                [
                    'key'           => 'field_responsavel_servicos_texto',
                    'instructions'  => 'Texto curto abaixo do título.',
                    'name'          => 'servicos_texto',
                    'label'         => 'Serviços — Texto',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'O Genoma oferece um portfólio completo de exames, organizado nas seguintes áreas:',
                ],
                [
                    'key'          => 'field_responsavel_servicos_categorias',
                    'instructions' => 'Cada linha é uma categoria que abre e fecha ao clicar, com a tabela de exames.',
                    'name'         => 'servicos_categorias',
                    'label'        => 'Serviços — Categorias de Exames',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar Categoria',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_responsavel_servicos_categoria_nome',
                            'instructions'  => 'Nome da categoria (ex.: Citologia).',
                            'name'          => 'nome',
                            'label'         => 'Nome da Categoria',
                            'type'          => 'text',
                        ],
                        [
                            'key'           => 'field_responsavel_servicos_categoria_aberto',
                            'name'          => 'aberto',
                            'label'         => 'Aberta por padrão?',
                            'type'          => 'true_false',
                            'ui'            => 1,
                            'default_value' => 0,
                            'instructions'  => 'Exibe a descrição e a lista de exames já expandida ao carregar a página.',
                        ],
                        [
                            'key'          => 'field_responsavel_servicos_categoria_descricao',
                            'name'         => 'descricao',
                            'label'        => 'Descrição (exibida quando expandida)',
                            'type'         => 'textarea',
                            'rows'         => 4,
                            'instructions' => 'Opcional. Deixe em branco se a categoria não tiver texto de introdução.',
                        ],
                        [
                            'key'          => 'field_responsavel_servicos_categoria_exames',
                            'instructions' => 'Exames da categoria, um por linha.',
                            'name'         => 'exames',
                            'label'        => 'Exames da Categoria',
                            'type'         => 'repeater',
                            'layout'       => 'table',
                            'min'          => 0,
                            'max'          => 0,
                            'button_label' => 'Adicionar Exame',
                            'sub_fields'   => [
                                [
                                    'key'   => 'field_responsavel_servicos_exame_nome',
                                    'instructions' => 'Nome do exame.',
                                    'name'  => 'nome',
                                    'label' => 'Nome',
                                    'type'  => 'text',
                                ],
                                [
                                    'key'   => 'field_responsavel_servicos_exame_prazo',
                                    'name'  => 'prazo',
                                    'label' => 'Prazo',
                                    'type'  => 'text',
                                    'instructions' => 'Ex: 7 Dias',
                                ],
                                [
                                    'key'   => 'field_responsavel_servicos_exame_amostra',
                                    'name'  => 'amostra',
                                    'label' => 'Tipo de Amostra',
                                    'type'  => 'text',
                                    'instructions' => 'Ex: Lâminas Ou Fluídos',
                                ],
                            ],
                        ],
                    ],
                ],

                // ── Resultados dos exames ────────────────────────────────
                [
                    'key'           => 'field_responsavel_resultados_eyebrow',
                    'instructions'  => 'Texto curto exibido acima do título da seção (ex.: SERVIÇOS).',
                    'name'          => 'resultados_eyebrow',
                    'label'         => 'Resultados — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Exames',
                ],
                [
                    'key'           => 'field_responsavel_resultados_titulo',
                    'name'          => 'resultados_titulo',
                    'label'         => 'Resultados — Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Use uma quebra de linha para controlar onde o título deve quebrar.',
                    'default_value' => 'Resultados dos exames',
                ],
                [
                    'key'           => 'field_responsavel_resultados_texto',
                    'name'          => 'resultados_texto',
                    'label'         => 'Resultados — Texto',
                    'type'          => 'textarea',
                    'rows'          => 8,
                    'instructions'  => 'Use uma linha em branco entre parágrafos.',
                    'default_value' => "Os resultados são liberados dentro dos prazos estabelecidos e enviados ao médico-veterinário solicitante, que é o profissional indicado para interpretar os exames e orientar o responsável sobre os próximos passos no cuidado com o pet.\n\nAlém disso, o responsável recebe um protocolo com usuário e senha para consultar os resultados diretamente em nosso site, de forma prática e segura.\n\nPara exames de rotina, a liberação costuma ser feita com agilidade, ajudando a acelerar o início do tratamento quando necessário.",
                ],
                [
                    'key'           => 'field_responsavel_resultados_imagem',
                    'instructions'  => 'Foto ao lado do texto.',
                    'name'          => 'resultados_imagem',
                    'label'         => 'Resultados — Imagem',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                ],

                // ── Benefícios ────────────────────────────────────────────
                [
                    'key'           => 'field_responsavel_beneficios_eyebrow',
                    'instructions'  => 'Texto curto exibido acima do título da seção (ex.: SERVIÇOS).',
                    'name'          => 'beneficios_eyebrow',
                    'label'         => 'Benefícios — Etiqueta',
                    'type'          => 'text',
                    'default_value' => 'Benefícios',
                ],
                [
                    'key'           => 'field_responsavel_beneficios_titulo',
                    'instructions'  => 'Título principal da seção.',
                    'name'          => 'beneficios_titulo',
                    'label'         => 'Benefícios — Título',
                    'type'          => 'text',
                    'default_value' => 'Nosso compromisso com o seu pet',
                ],
                [
                    'key'           => 'field_responsavel_beneficios_texto',
                    'name'          => 'beneficios_texto',
                    'label'         => 'Benefícios — Texto de destaque',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Opcional. Aparece abaixo dos cards de benefícios.',
                    'default_value' => 'Tudo para garantir mais segurança e cuidado com a saúde do seu melhor amigo 💙',
                ],
                [
                    'key'          => 'field_responsavel_beneficios_itens',
                    'instructions' => 'Cada linha é um card com ícone e texto. Fica melhor com 4 itens (uma linha no computador).',
                    'name'         => 'beneficios_itens',
                    'label'        => 'Benefícios — Itens',
                    'type'         => 'repeater',
                    'layout'       => 'block',
                    'min'          => 0,
                    'max'          => 0,
                    'button_label' => 'Adicionar benefício',
                    'sub_fields'   => [
                        [
                            'key'           => 'field_responsavel_beneficios_item_icone',
                            'instructions'  => 'Ícone em SVG ou PNG com fundo transparente.',
                            'name'          => 'icone',
                            'label'         => 'Ícone',
                            'type'          => 'image',
                            'return_format' => 'array',
                            'preview_size'  => 'medium',
                        ],
                        [
                            'key'           => 'field_responsavel_beneficios_item_texto',
                            'instructions'  => 'Texto curto do card (até 3 linhas).',
                            'name'          => 'texto',
                            'label'         => 'Texto',
                            'type'          => 'text',
                            'default_value' => 'Qualidade e confiabilidade nos exames',
                        ],
                    ],
                ],

                // ── Rodapé (sobrescreve o CTA do banner só nesta página) ───
                [
                    'key'           => 'field_responsavel_footer_cta_titulo',
                    'name'          => 'footer_cta_titulo',
                    'label'         => 'Rodapé — CTA Título',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'instructions'  => 'Sobrescreve o título do banner de CTA do rodapé só nesta página. Deixe em branco para usar o padrão de Opções do Tema.',
                    'default_value' => "Entre em contato com\na nossa equipe.",
                ],
                [
                    'key'           => 'field_responsavel_footer_cta_primario_texto',
                    'name'          => 'footer_cta_primario_texto',
                    'label'         => 'Rodapé — CTA Primário (Texto)',
                    'type'          => 'text',
                    'instructions'  => 'Sobrescreve o texto do botão principal do banner de CTA do rodapé só nesta página. Deixe em branco para usar o padrão de Opções do Tema.',
                    'default_value' => 'Fale conosco pelo WhatsApp',
                ],
                [
                    'key'           => 'field_responsavel_footer_cta_primario_link',
                    'instructions'  => 'Endereço do botão principal do banner. Em branco, usa o das Opções do Tema.',
                    'name'          => 'footer_cta_primario_link',
                    'label'         => 'Rodapé — CTA Primário (Link)',
                    'type'          => 'text',
                    'default_value' => '#',
                ],
                [
                    'key'           => 'field_responsavel_footer_cta_mostrar_secundario',
                    'instructions'  => 'Desligado: o banner mostra só o botão principal (roxo).',
                    'name'          => 'footer_cta_mostrar_secundario',
                    'label'         => 'Rodapé — Mostrar Botão Secundário',
                    'type'          => 'true_false',
                    'ui'            => 1,
                    'default_value' => 0,
                ],
                [
                    'key'               => 'field_responsavel_footer_cta_secundario_texto',
                    'instructions'      => 'Texto do segundo botão do banner. Em branco, usa o das Opções do Tema.',
                    'name'              => 'footer_cta_secundario_texto',
                    'label'             => 'Rodapé — CTA Secundário (Texto)',
                    'type'              => 'text',
                    'default_value'     => 'Fale Conosco',
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_responsavel_footer_cta_mostrar_secundario',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],
                [
                    'key'               => 'field_responsavel_footer_cta_secundario_link',
                    'instructions'      => 'Endereço do segundo botão do banner. Em branco, usa o das Opções do Tema.',
                    'name'              => 'footer_cta_secundario_link',
                    'label'             => 'Rodapé — CTA Secundário (Link)',
                    'type'              => 'text',
                    'default_value'     => '#',
                    'conditional_logic' => [
                        [
                            [
                                'field'    => 'field_responsavel_footer_cta_mostrar_secundario',
                                'operator' => '==',
                                'value'    => '1',
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }
}
